### ISSUE TITLE
the dilation parameters

### ISSUE THREAD

**Issue by scholltan** [JiaRenChang/PSMNet#1]
hi, thanks for your  awesome job. I have a question: the parameters in the feature_extraction (layer3 and layer4), the dilation is 1 and 2, while in the paper is 2 and 4. So which one is right?  Thank you !

**Comment by JiaRenChang** [comment]
Hi,
    We used both of two dilation rate (1, 2 and 2, 4) in the experiment.
    Please refer to the Table 2.
    The last row indicated that we used  half dilation rate (1 ,2).
Jia-Ren

**Comment by scholltan** [comment]
thank you ！

**Comment by scholltan** [comment]
will you guys release the pretrained model？

**Comment by JiaRenChang** [comment]
Hi,
    We shared the model that we used on KITTI 2015.
    Please refer to README.
Jia-Ren
