### ISSUE TITLE
Size mismatch error

### ISSUE THREAD

**Issue by weihaosky** [JiaRenChang/PSMNet#112]
I am using submission.py to test KITTI 2015 dataset. But in 
`post = F.relu(self.conv5(out)+pre, inplace=True) ` 
this line, it give me an error as
> The size of tensor a (14) must match the size of tensor b (13) at non-singleton dimension 2

The shape of pre is [1, 64, 13, 48, 156] but the shape of self.conv5(out) is [1, 64, 14, 48, 156].

Why is this? Many thanks

**Comment by zstu-lly** [comment]
How did you solve this?
