### ISSUE TITLE
About GPU memory

### ISSUE THREAD

**Issue by K-Akechi** [JiaRenChang/PSMNet#121]
Hi, when I use a single TITAN X(Pascal) to train the model with default settings, it just come out with  RuntimeError: CUDA out of memory. Does it means multiple GPUs are required for this model or I can lower the batchsize?
Thanks

**Comment by HaixiongLi** [comment]
hey, did you solve your problems? I missed the same question with you

**Comment by K-Akechi** [comment]
Actually I set batchsize to 3 when training on TITAN X with 12 GB memory.
