### ISSUE TITLE
您好，我有几个问题想向您请教。

### ISSUE THREAD

**Issue by fighterzzzh** [JiaRenChang/PSMNet#145]
我刚跑完了自己修改过的psmn的代码，但显卡受限，batchsize=1，结果不是很好。
请问您如果使用batchsize=1是不是效果会不理想？
另外如果batchsize=1，BatchNormalization是否会有作用？
还有一个问题，为什么不把kitti2012也作为预训练，然后去训练kitti2015呢。我打算去做这件事。
问题有点多哈，如您能万分忙碌之中抽空回答，万分感谢。

**Comment by JiaRenChang** [comment]
@fighterzzzh 
Batch size = 1時 BN與Instance Norm是相等的，還是會有作用，但如您所訓練的，結果可能沒這麼好
是可以將KITTI2012也下去做訓練的
但我們在這是為了區分兩個dataset

**Comment by fighterzzzh** [comment]
明白了，谢谢
