### ISSUE TITLE
Can this pretrained model be directly used to match stereo images?

### ISSUE THREAD

**Issue by feiyangsuo** [JiaRenChang/PSMNet#149]
I tried to use it to match some underwater images, since I don't have training sets of underwater image disparity. I got very bad results then .
This is my image to match:
![](https://user-images.githubusercontent.com/47778268/64320632-8b247100-cff1-11e9-94b0-3eeb31480b10.jpg)
I noticed there are big black border around the image (which is caused by rectification), could it be the reason why I got bad matching result?
And this is what disparity map I got, Actually it's not almost 0 as I said before:
![](https://user-images.githubusercontent.com/47778268/64321438-1b16ea80-cff3-11e9-9b32-16960b68e038.jpg)
Input image is be warped into 324*1248, as indicated in the code.

**Comment by feiyangsuo** [comment]
And this is my image to match:
![total](https://user-images.githubusercontent.com/47778268/64320632-8b247100-cff1-11e9-94b0-3eeb31480b10.jpg)
I noticed there are big black border around the image (which is caused by rectification), could it be the reason why I got bad matching result?

**Comment by feiyangsuo** [comment]
And this is what disparity map I got, Actually it's not almost 0 as I said before:
![disp](https://user-images.githubusercontent.com/47778268/64321438-1b16ea80-cff3-11e9-9b32-16960b68e038.jpg)
I also have a question: why the input image should be padded into 324*1248?

**Comment by JiaRenChang** [comment]
@feiyangsuo 
Hi, I upload a new script to test stereo pairs.
Please check README.

**Comment by feiyangsuo** [comment]
@JiaRenChang 
Hi. Thanks for your answer and script. Yet I still got disparity map like before.
/home/flicic/Documents/Python/PSMNet-master/PSMNet-master/disparity.png
I also tried cropping off the black brink in the images, but it's not improving the result.

**Comment by soulslicer** [comment]
it was only trained on Kitti though. you need to train on your own dataset
