### ISSUE TITLE
question about maximum disparity

### ISSUE THREAD

**Issue by MASTERCHIEF343** [JiaRenChang/PSMNet#161]
Hi, thanks to your code.I have some problems about maximum disparity in cost volume building.I see in your code, you build cost volume use maximum disparity/4, and in the end you upsample it as original maximum disparity.I just don't know the reason for disparity/4, maybe this will lost disparity information.

**Comment by MASTERCHIEF343** [comment]
Oh, I just figure it out.

**Comment by August0424** [comment]
> Oh, I just figure it out.

I had the same question when reading the code. Later I realized that it is due to the 4x spatial downsampling
