### ISSUE TITLE
the problem about submit result on "KITTI Evaluation Benchmark "

### ISSUE THREAD

**Issue by wenyang1112** [JiaRenChang/PSMNet#163]
I submit my result on stereo 2015, then I receive a letter from "KITTI Evaluation Benchmark ", it give me a link to check the result. But when I click the link, it show me the error: ERROR: Result key 3708644dc4ab21dc7e6405e2d0c2d31f835 not registered with user fe4d4b5364cb33b1b410d3d27e2aae1. I don't know how to solve it. Could you give me some advice? Thank you!
ps: my zip only include disp_0 floder, because I just want to submit the stereo 2015 test set result

**Comment by JiaRenChang** [comment]
@wenyang1112 
Hi, you should ask CVLIBS (http://www.cvlibs.net/).

**Comment by wenyang1112** [comment]
thanks for your reply
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Jia-Ren Chang"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月16日(星期一) 上午9:38
 收件人:&nbsp;"JiaRenChang/PSMNet"<PSMNet@noreply.github.com&gt;;
 抄送:&nbsp;"wy"<2453079161@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [JiaRenChang/PSMNet] the problem about submit result on "KITTI Evaluation Benchmark " (#163)

 

 
@wenyang1112
Hi, you should ask CVLIBS (http://www.cvlibs.net/).
