### ISSUE TITLE
About finetune

### ISSUE THREAD

**Issue by zhangguanghui1** [JiaRenChang/PSMNet#18]
I think, in finetune.py
Line 150： max_acc=0 ---> min_err=100
Line 178/179: if total_test_loss/len(TestImgLoader)*100 > max_acc:
max_acc = total_test_loss/len(TestImgLoader)*100 --->
if total_test_loss/len(TestImgLoader)*100 < min_err:
min_err = total_test_loss/len(TestImgLoader)*100
Line 194: print(max_acc) ---> print(min_err)
I'm not sure if it is right ? Thank you !

**Comment by zhangguanghui1** [comment]
Sorry, just ingore above.
I think, in finetune.py
Line 150： max_acc=0 ---> min_err=100
Line 178/179: if total_test_loss/len(TestImgLoader)*100 > max_acc:
                          max_acc = total_test_loss/len(TestImgLoader)*100 --->
                       if total_test_loss/len(TestImgLoader)*100 < min_err:
                           min_err = total_test_loss/len(TestImgLoader)*100
Line 194: print(max_acc) ---> print(min_err)
I'm not sure if it is right ? Thank you !

**Comment by JiaRenChang** [comment]
@zhangguanghui1 
We have fixed those codes.
The finetune.py reported 3-px "error" now.

**Comment by zhangguanghui1** [comment]
Thanks for your reply, I saw the 3-px error and what you modified,  just as 'return 1-(float(torch.sum(correct))/float(len(index[0])))'.　What I want to express is, I think, after the modify，there is still the small problem that I wrote above. 

Of course, maybe I haven't  fully understood it. I'll look at it more carefully~

**Comment by zhangguanghui1** [comment]
@JiaRenChang Thanks for your reply, I saw the 3-px error and what you modified, just as 'return 1-(float(torch.sum(correct))/float(len(index[0])))'.　What I want to express is, I think, after the modify，there is still the small problem that I wrote above.

Of course, maybe I haven't fully understood it. I'll look at it more carefully~
