### ISSUE TITLE
The spp module in the code is different from the paper, that is, the convolution kernel paper is 3, and the code is 1?

### ISSUE THREAD

**Issue by Peterisfar** [JiaRenChang/PSMNet#184]
![image](https://user-images.githubusercontent.com/31852119/82747638-bd6b3e00-9dcd-11ea-8a51-73eebf7df8aa.png)
![image](https://user-images.githubusercontent.com/31852119/82747662-f4d9ea80-9dcd-11ea-9cc3-92db7c87f8a9.png)

**Comment by JiaRenChang** [comment]
We used 1x1 conv for SPP module here.
In the paper, it is a typo there.
However, 3x3 will not harm the performance of PSMNet.

**Comment by Peterisfar** [comment]
> In the paper, it is a typo there.

thanks
