### ISSUE TITLE
作者你好，我想 请问有关我再次复现代码效果变差的原因

### ISSUE THREAD

**Issue by kearcer** [JiaRenChang/PSMNet#190]
去年我使用python2复现过您的代码，在KITTI2015上2.43%的错误率，虽然未能达到论文上的精度，但我认为我的配置和操作应该是没问题的，今年我看见您又更新python3，但是采用了python3.6+torch1.4+torchvision0.5.0复现了代码，但是结果却差了很多，如下图所示在图像的上部有大块的误匹配点，细节也不如去年使用python2跑的效果要好，KITTI2015整体错误率高达5%。想请问一下，我错误的可能性在哪里？
![对](https://user-images.githubusercontent.com/40928138/87495465-1182f800-c684-11ea-85d6-3a66611eb79d.png)
这是我去年的KITTI2015测试集第54张图片
![错](https://user-images.githubusercontent.com/40928138/87495479-1647ac00-c684-11ea-9c16-4e709d999ad7.png)
这是我今年的KITTI2015测试集54张图片

**Comment by JiaRenChang** [comment]
您好:
有可能是因為unsmaple的關係
您可以嘗試 在每個upsample的後面加上參數 align_corners=True

**Comment by kearcer** [comment]
@JiaRenChang 感谢作者的回复，这对我非常有用，我正尝试修改以后重新训练它。

**Comment by kearcer** [comment]
我想我找到原因了，去年我采用的pretrained2015模型训练300个epoch，今年选了senceflow预训练模型，我的粗心大意打扰到了您，非常抱歉，同时我再次感谢你的回复
