### ISSUE TITLE
Would you please provides the PSMNet model pertrained on Scene Flow

### ISSUE THREAD

**Issue by j-c-zhang** [JiaRenChang/PSMNet#2]
Hello, Jia-Ren Chang.

I want to conduct some experiments based on your work.
However, I have trouble in reproducing your experiment result on KITTI Stereo Evaluation 2015 due to the lack of  PSMNet model pertrained on Scene Flow dataset.
Would you please provides the PSMNet model pertrained on Scene Flow for me?

Thank you very much!

**Comment by JiaRenChang** [comment]
Hi,
    We shared the model that we used on KITTI 2015.
    Please refer to README.
Jia-Ren

**Comment by j-c-zhang** [comment]
I got it! 
Thank you!

**Comment by scholltan** [comment]
@j-c-zhang have you decompressed the .tar file correctly? I got the following error:
   tar -xvf pretrained_model_KITTI2015.tar 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

**Comment by JiaRenChang** [comment]
@scholltan 
You can use torch.load() to load the model

**Comment by zhangguanghui1** [comment]
@JiaRenChang The model "pretrained_model_KITTI2015.tar" I download from your link. It is trained (epoch 100 times ) on SenceFlowData firstly, and then finetune (epoch 300 times) on KITTI 2015 training dataset, right? Thanks a lot!

**Comment by zhangguanghui1** [comment]
@JiaRenChang The model "pretrained_model_KITTI2015.tar" I download from your link. It is trained (epoch 10 times ) on SenceFlowData firstly, and then finetune (epoch 300 times) on KITTI 2015 training dataset, right? Thanks a lot!

**Comment by bryanyzhu** [comment]
@JiaRenChang Hi, thanks for the wonderful work. I understand that you already provide the trained model for KITTI2015. But is it ok to share your pre-trained model on SceneFlow dataset as well? Because not all people are working on KITTI, a pre-trained model on SceneFlow would be much more helpful. Thank you.
