### ISSUE TITLE
monkaa_path = filepath + [x for x in image if 'monkaa' in x][0]  IndexError: list index out of range

### ISSUE THREAD

**Issue by zhangmin4215** [JiaRenChang/PSMNet#204]
Hello, when I run main.py, I meet this kind of problem, and I cannot solve it. Hope your help! Thank you.

Traceback (most recent call last):
  File "main.py", line 41, in <module>
    all_left_img, all_right_img, all_left_disp, test_left_img, test_right_img, test_left_disp = lt.dataloader(args.datapath)
  File "/Users/zhangmin/Desktop/PSMNet-master/dataloader/listflowfile.py", line 21, in dataloader
    monkaa_path = filepath + [x for x in image if 'monkaa' in x][0]
IndexError: list index out of range

**Comment by Miaowei-HNU** [comment]
hello ,Have you solved this problem

**Comment by N1etz3che** [comment]
你解决这个问题了吗
