### ISSUE TITLE
What is the stride for average pooling in SPP?

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [JiaRenChang/PSMNet#206]
Hi,

There are 4 fixed size average pooling modules in the SPP: 64x64, 32x32, 16x16, 8x8

If the input size is HxW, what would be the output size on passing this input through the above pooling modules?
If the stride is 1, the size would remain nearly same. However, if the strides are 64, 32, 16, and 8 respectively, the output size will change significantly: H/64 x W/64, H/32 x W/32, H/16 x W/16, and H/8 x W/8.

Please guide me through this.

**Comment by JiaRenChang** [comment]
Hi, @Diksha-Moolchandani,  
    The strides of SPP are the same with its window size, i.e., 64, 32,16 and 8.
    We further use bilinear interpolation for upsampling features.

**Comment by Diksha-Moolchandani** [comment]
Thanks a lot
