### ISSUE TITLE
There is a problem with the 3-pixel error code in fintune

### ISSUE THREAD

**Issue by Baboom-l** [JiaRenChang/PSMNet#212]
When I change the size of the batch, the same model calculates different errors！！！
batch=1 ，3-pixel error=1.520
batch=3，3-pixel error change to  1.623

Can anyone explain the problem？

**Comment by Baboom-l** [comment]
@JiaRenChang Can you provide the kitti2015 pre training model of 300epoch in the paper for me to test，The 1000 epoch model is difficult to reflect the real effect of the model in the val dataset

**Comment by Baboom-l** [comment]
Happily, I think I may have found the problem. There is an error in the calculation of less than 5% in fintune. I think it might be because  it's disp_ True and true_ Disp points to the same memory.
So you can have an easy way to fix it，as follow：

correct = (disp_true[index[0][:], index[1][:], index[2][:]] < 3)|(disp_true[index[0][:], index[1][:], index[2][:]] < true_disp[index[0][:], index[1][:], index[2][:]]*0.05)    

change to

p5 = true_disp[index[0][:], index[1][:], index[2][:]]*0.05
correct = (disp_true[index[0][:], index[1][:], index[2][:]] < 3) | (disp_true[index[0][:], index[1][:], index[2][:]]<p5)

**Comment by JiaRenChang** [comment]
Hi, @Baboom-l
   Thanks for pointing out the bug.  However, the 3px errors in the paper are calculated by the Matlab code from official KITTI site.
   I suggest to change the [line 128](https://github.com/JiaRenChang/PSMNet/blob/ce82dfd9e6ead62e290b606f1197fcc768a67eae/finetune.py#L128) with deepcopy, i. e., `true_disp = copy.deepcopy(disp_true)`.
