### ISSUE TITLE
About trilinear upsampling

### ISSUE THREAD

**Issue by heguohao0728** [JiaRenChang/PSMNet#214]
Hi @JiaRenChang, nice work.
In your parper, Figure 1, after you get cost1, cost2 and cost3, it seems you use bilinear upsampling.
But in the code, you use trilinear upsampling, like
`cost3 = F.upsample(cost3, [self.maxdisp, left.size()[2], left.size()[3]], mode='trilinear')`
What's the difference? Is bilinear worse than trilinear?
Thank you so much.

**Comment by JiaRenChang** [comment]
@heguohao0728 

It is the same thing.  Trilinear is for 3D tensor as well as bilinear is for 2D tensor.

[Trilinear_interpolation](https://en.wikipedia.org/wiki/Trilinear_interpolation)

**Comment by heguohao0728** [comment]
Oh...I got it, Thanks!
