### ISSUE TITLE
一个关于预训练的问题

### ISSUE THREAD

**Issue by Baboom-l** [JiaRenChang/PSMNet#215]
冒昧的用中文提问您，因为我的英文无法准确表达我的困境。首先我在此感谢您对该项目的开源。我最近在您的项目上进行了改进（添加了部分模块），但我在训练时直接加载了您给出的在Scene Flow上预训练的权重，并使用kitti2015的训练集继续训练至loss收敛，test验证精度提升到2.1，但我没有使用Scene Flow从头训练。

       因此我困惑于是否应该将修改的模型用Scene Flow从头开始训练一个预训练模型，这相比直接加载您的部分预训练权重对模型最后的精度会有很大的影响吗？(因为实验室卡少，如果没有多大提升我可能只能放弃它了）如能回复，不胜感激！

**Comment by JiaRenChang** [comment]
@Baboom-l 
預訓練你新增的模塊應該是可以有些許的表現提高
這問題應該是你要實際應用呢? 還是拼精度?
如果是要應用，那麼能在最少資源下訓練即可
如果是要拼精度發論文，那僅可能的把模型訓練到最佳

**Comment by Baboom-l** [comment]
tanks
