### ISSUE TITLE
finetune.py 131 line

### ISSUE THREAD

**Issue by jangsooyoung** [JiaRenChang/PSMNet#229]
simple fix  : 
finetune.py 131 line
       disp_true[index[0][:], index[1][:], index[2][:]] = np.abs(true_disp[index[0][:], index[1][:], index[2][:]]-pred_disp[index[0][:], 0, index[1][:], index[2][:]]) # add  ,0, 
     Space & tab adjustment

**Comment by xiangweifeng** [comment]
pred_disp = pred_disp.squeeze(1)
