### ISSUE TITLE
EPE too large

### ISSUE THREAD

**Issue by rebecca0011** [JiaRenChang/PSMNet#231]
我使用10个epochs对scenenflow进行预训练，
将KITTI划分为训练和验证集，预训练模型验证KITTI2015中验证集图像得到EPE为19.23，利用KITTI2015中训练集精化100个epochs，得到EPE为20.11。
结果和我预想的差异很大，请问可能是什么原因导致的呢？
我使用的是CUDA11.2，pytorch1.8.0，batchsize为1.

**Comment by JiaRenChang** [comment]
Hi, @rebecca0011 
     你的sceneflow跟KITTI都是用batchsize=1做訓練的嗎?
      batchsize太小的效果很差
Jia-Ren

**Comment by rebecca0011** [comment]
> Hi, @rebecca0011 你的sceneflow跟KITTI都是用batchsize=1做訓練的嗎? batchsize太小的效果很差 Jia-Ren

是的，我使用的batchsize都是1。我将使用较大的batchsize重新训练。
