### ISSUE TITLE
can't extract pretrained model

### ISSUE THREAD

**Issue by leizhenyu-lzy** [JiaRenChang/PSMNet#241]
![image](https://user-images.githubusercontent.com/54441823/233829417-e35c64cc-dce2-44d2-8c37-ea75e0646587.png)

after i download it, i still can't extract it

![image](https://user-images.githubusercontent.com/54441823/233829447-3f430bf1-2428-4999-82f2-42aa7ab14356.png)

**Comment by leizhenyu-lzy** [comment]
in fact, only pretrained_sceneflow_new can be extracted

**Comment by thejauffre** [comment]
The .tar file itself is the checkpoint, you don't need to extract it
