### ISSUE TITLE
Some problems while training on CPU

### ISSUE THREAD

**Issue by SkeletonOne** [JiaRenChang/PSMNet#26]
Thanks for sharing your code on github. I ran into some problems while running your code on my laptop, am i able to run finetune.py or submission.py without CUDA installed?  While running submission.py it shows AssertionError: Torch not compiled with CUDA enabled. Besides, does finetune.py use the 'loadmodel' from the google drive download from your link? I am not able to type the right path of the model, anyone else face the same problem?

**Comment by JiaRenChang** [comment]
Hi, @SkeletonOne 
    You may add the argument of "--no-cuda True" to the command lines.

**Comment by SkeletonOne** [comment]
@JiaRenChang 
Thanks for answering my question, however the error still exists: AttributeError: 'module' object has no attribute '_cuda_getDevice'

**Comment by JiaRenChang** [comment]
@SkeletonOne 
You may try convert the trained model to cpu mode.
Try "model.cpu()" after loading model.
https://discuss.pytorch.org/t/loading-weights-for-cpu-model-while-trained-on-gpu/1032

**Comment by rintiunse** [comment]
@SkeletonOne  Can this code run on the pytorch without cuda? I think it's difficult to do.

**Comment by passion3394** [comment]
@rintiunse @SkeletonOne I have modified the author's code, and the code could inference on CPU, the inference time is much longer than GPU mode.

**Comment by passion3394** [comment]
please refer https://github.com/passion3394/PSMNet_CPU

**Comment by SkeletonOne** [comment]
@passion3394 Great work! It will surely benefit others a lot.
