### ISSUE TITLE
How many GPU needed when test on KITTI2015 and train on SceneFlowData?

### ISSUE THREAD

**Issue by HyuanTan** [JiaRenChang/PSMNet#3]
Hi, thanks for share. I wanted to test the model using `submission.py` on KITTI2015, but  encountered `out of memory`. I want to know how many GPU I need when training on SceneFlowData and testing on KITTI2015. 

Thanks!

**Comment by scholltan** [comment]
in the paper, they used 4 titan xp(~12G) with 3 batch on each.

**Comment by HyuanTan** [comment]
@scholltan Thanks! How many GPU(at least) needed for testing on a pair images of KITTI2015?

**Comment by JiaRenChang** [comment]
@HyuanTan 
Inference on a pair image of KITTI2015 spend around 4500 MB GPU memory on my machine.
I suggest that a GPU has at least 6 GB (1060 6GB is good!).

**Comment by HyuanTan** [comment]
@JiaRenChang OK, I got it. Thank you!

**Comment by HyuanTan** [comment]
@JiaRenChang Hi, I'm sorry to disturb you again. Now I have 11G free GPU and I can inference on a pair image of KITTI2015 only when I decrease `--maxdisp` to 96 or more less. How many GPU(at least) needed if I want to set the `--maxdisp` to 192(It is limited for me to get more GPU)?

Thanks!

**Comment by HyuanTan** [comment]
@JiaRenChang Thanks! According to your advice, I can inference on a pair image of KITTI2015 spend around 4500 MB GPU (maxdisp = 192) now.
