### ISSUE TITLE
About the crop size 544*960

### ISSUE THREAD

**Issue by chenchr** [JiaRenChang/PSMNet#30]
Hello. Thank you for the paper and code. I an confused about the dataloader for sceneflow dataset. As the image size of the dataset is 540*940, however, when in test mode, the [code](https://github.com/JiaRenChang/PSMNet/blob/master/dataloader/SecenFlowLoader.py#L70 )  crop the image to 544*960..  
```
else:
           w, h = left_img.size
           left_img = left_img.crop((w-960, h-544, w, h))
           right_img = right_img.crop((w-960, h-544, w, h))
           processed = preprocess.get_transform(augment=False)  
           left_img       = processed(left_img)
           right_img      = processed(right_img)

           return left_img, right_img, dataL
```
Could you explain why it is doing for ? Thanks!

**Comment by JiaRenChang** [comment]
Hi,  we want to pad the width and height of images to multiple of 32.

**Comment by chenchr** [comment]
Oh... Thanks for your reply. So for any pair of stereo image, I need to pad it if I use PSMNet to predict the disparity ?

**Comment by JiaRenChang** [comment]
Yes. If image size is not appropriate,  the feature may not to sum them because the dimension.

**Comment by chenchr** [comment]
Thanks！
