### ISSUE TITLE
Question about the pretrained model

### ISSUE THREAD

**Issue by hhwxxx** [JiaRenChang/PSMNet#33]
@JiaRenChang Hello, thanks for your wonderful work!
I am doing some experiments based on your work. But I am confused about the pretrained model you provide. Which part of the KITTI 2015 dataset is used for training the PSMNet model you provide? The whole 200 training images or 160 training images you split?
If the pretrained model using the whole 200 training images, would you please provide the model training on the 160 images? Or could you provide the PSMNet model pretrained on Scene Flow dataset?
Any help would be appreciated.

**Comment by JiaRenChang** [comment]
The number of  other 40 images for validation were listed below:
[1,3,6,20,26,35,38,41,43,44,49,60,67,70,81,84,89,97,109,119,122,123,129,130,132,134,141,144,152,158,159,165,171,174,179,182,186,187,196]

The final model that we provided here is training on whole KITTI dataset.

**Comment by hhwxxx** [comment]
@JiaRenChang Thank you very much!
And sorry for disturbing you again. Do you have any plan to release the PSMNet model pretrained on SceneFlow dataset?

**Comment by zhFuECL** [comment]
Same question with @hhwxxx. Thx
