### ISSUE TITLE
The pretrained model from google drive is not working?

### ISSUE THREAD

**Issue by liutaotao369** [JiaRenChang/PSMNet#4]

**Comment by liutaotao369** [comment]
Sorry it is working now, but i wonder why this pretrained model tar file cannot be extracted

**Comment by JiaRenChang** [comment]
@liutaotao369 
Hi, this post may answer your question.
[Link](http://forums.fast.ai/t/which-format-is-better-for-pytorch-saved-model/5018)

**Comment by qewtqwqqq** [comment]
@liutaotao369 I have the same problem, the .tar cannot be extract. Did you solve it?
