### ISSUE TITLE
Some puzzles on the cost volume

### ISSUE THREAD

**Issue by kingsleyluoxin** [JiaRenChang/PSMNet#50]
```
for i in range(self.maxdisp/4):
            if i > 0 :
             cost[:, :refimg_fea.size()[1], i, :,i:]   = refimg_fea[:,:,:,i:]
             cost[:, refimg_fea.size()[1]:, i, :,i:] = targetimg_fea[:,:,:,:-i]
            else:
             cost[:, :refimg_fea.size()[1], i, :,:]   = refimg_fea
             cost[:, refimg_fea.size()[1]:, i, :,:]   = targetimg_fea
```
This piece of codes has puzzled me. I am wondering why there would be negtive numbers, if using range() ,should all the iteration be positive?
Besides, I am also wondering the way to concat two feature maps. How to understand the last dimension where in code "if  i > 0", how to understand the index i: and :-i？

**Comment by JiaRenChang** [comment]
@kingsleyluoxin 
Hi, you may read this https://stackoverflow.com/questions/14419206/what-does-1-mean-in-python .

**Comment by kingsleyluoxin** [comment]
@JiaRenChang
Thank you so much for your reply. Actually, I understand what -1 means in python. What  puzzles me is actually the dimension of cost volume described in the paper is four, but here it becomes five. I want to know what this extra dimension means.

**Comment by JiaRenChang** [comment]
@kingsleyluoxin 
The extra dimension is batch size.
So, the cost volume is a 5-D tensor which has Batch size X Channel X Disparity X Height X Width.

**Comment by kingsleyluoxin** [comment]
@JiaRenChang
Got it. Thanks a ton. So one more question. Why the last dimension in the codes is related to disparity？ That is, why we need to cut it according to the value of disparity when disparity is positive？

**Comment by JiaRenChang** [comment]
@kingsleyluoxin 
The region that we can not concatenate both left and right feature will be cut, and replace with 0.
