### ISSUE TITLE
how to show  the disparity map in color mode ?

### ISSUE THREAD

**Issue by hurricane2018** [JiaRenChang/PSMNet#56]
Thank you for your wonderful work.
I  test the provided code, one disparity map can be as follow:
![image](https://user-images.githubusercontent.com/36166137/41197576-c0656024-6c31-11e8-979a-9746bd7f77ca.png)

But how to show the disparity map in color mode ? like 
![image](https://user-images.githubusercontent.com/36166137/41197577-da640f70-6c31-11e8-841c-88447c2de17e.png)

how to compute and save the error map in color mode ?
![image](https://user-images.githubusercontent.com/36166137/41197579-e56063f6-6c31-11e8-88c9-a093a68f931c.png)

Thank you very much!

**Comment by kalanityL** [comment]
@hurricane2018 could you explain how you got the colored depth map from the greyscale output of the network?

**Comment by zhFuECL** [comment]
@kalanityL you can download the development toolkit here http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo

**Comment by kalanityL** [comment]
I had missed this one - thanks a lot
