### ISSUE TITLE
Finetuned on all Kitti means train + test of kitti2015? or of kitti2012 + kitti2015? 

### ISSUE THREAD

**Issue by kalanityL** [JiaRenChang/PSMNet#60]
Hi, 

You write that in order to have a better pretrained model available, you released a model trained from scratch on SeneFlow, then fined tuned on "all" kitti, meaning including also test images in the training.  

Do you mean all train and test for Kitti2015 only? and Kitti2012 is not at all in your finetuning? 

Question being, if I am runing submission.py on a test image from Kitti2015, I understood this image was part of the training of pretrained_model_KITTI2015.tar. 

But if I run submission on a test or train image of Kitti2012, this image was not part of the training because it is finetune on Kitti2015 only. Or when you say "all kitti" you mean test and train images of Kitti2015 and Kitti2012 as well ?

**Comment by JiaRenChang** [comment]
@kalanityL 
Sorry about confusing.
Kitti datasets were trained and tested separately.
For kitti 2015, we finetuned on kitti 2015 training set and tested on kitti 2015.
For kitti 2012, we did the same thing.

**Comment by kalanityL** [comment]
Ah ok thank you. 
And thanks again for the great work :)
