### ISSUE TITLE
Much less accurate than paper results when testing

### ISSUE THREAD

**Issue by kalanityL** [JiaRenChang/PSMNet#63]
Hi, 

I ran the net with pretrained_model_KITTI2015 on the same image than the home page of the git to compare my output with expected one. 

Initial left pic: 
![000004_10](https://user-images.githubusercontent.com/28892491/41647665-9e37c6b2-747f-11e8-985c-57f22f67f7eb.png)

Network output: 
![000004_10](https://user-images.githubusercontent.com/28892491/41647678-a5e67e62-747f-11e8-8ed8-1e3fc0735b15.png)

Colorization using kitti scene flow devkit disp_to_color.m:
![000004_10](https://user-images.githubusercontent.com/28892491/41647690-ac2de206-747f-11e8-9c02-7403d1072c53.png)

Your output on the home page:
![ref_depth](https://user-images.githubusercontent.com/28892491/41647727-be8e6f4c-747f-11e8-8cd5-8101abe9717d.png)

Could you let me know what I am doing wrong? 

Modules: 
Ubuntu 16.04
Python 2.7.12
torch   0.4.0   
torchvision   0.2.0   

Thank you

**Comment by hurricane2018** [comment]
Same question

2018-06-20 3:48 GMT-05:00 kalanityL <notifications@github.com>:

**Comment by hurricane2018** [comment]
In my case, the disparity could be  46.65 %

![image](https://user-images.githubusercontent.com/36166137/41662069-e0a38302-7465-11e8-978e-33906c1ff563.png)

Could you guys help me ?

**Comment by kalanityL** [comment]
got 37.56 ... 
it is better rendering than when I apply the disp_to_color.m function... but still not the expected result. 
![screenshot from 2018-06-20 16-46-07](https://user-images.githubusercontent.com/28892491/41662328-856df5e6-74a9-11e8-86fe-2f330acc2136.png)

**Comment by kalanityL** [comment]
got 0.27% on train2015 img 000000_10.png
![screenshot from 2018-06-20 16-59-20](https://user-images.githubusercontent.com/28892491/41663123-5dc29626-74ab-11e8-8576-5682abc56cde.png)

**Comment by hurricane2018** [comment]
Could you share the evaluation code with me?

2018-06-20 9:00 GMT-05:00 kalanityL <notifications@github.com>:

**Comment by kalanityL** [comment]
I answer on your issue. Can you remove your comments from this post. Cause posting your issue on several different issues is not very helpfull

**Comment by hurricane2018** [comment]
ok. already remove that

**Comment by InnovArul** [comment]
Did you find out the reason yet?

**Comment by kalanityL** [comment]
No. If I do I would update here. 
Anyone having same outputs and same range of colors?

**Comment by kalanityL** [comment]
Colorization is changing depending on the max_disp argument given to the matlab disp_to_color.m
max_disp = 50:
![000004_10](https://user-images.githubusercontent.com/28892491/41819776-f30386de-77ce-11e8-93a0-c40a9f1bb56e.png)


max_disp = 75:
![000004_10](https://user-images.githubusercontent.com/28892491/41819778-fa17e186-77ce-11e8-93a0-a308c25403d1.png)


max_disp = 100:
![000004_10](https://user-images.githubusercontent.com/28892491/41819779-ff00ca5a-77ce-11e8-806c-039f04b315c5.png)


max_disp = 150:
![000004_10](https://user-images.githubusercontent.com/28892491/41819780-0559625e-77cf-11e8-8252-849352538855.png)


max_disp = 192:
![000004_10](https://user-images.githubusercontent.com/28892491/41819782-0fbca8be-77cf-11e8-91a1-30bb06b793a2.png)

**Comment by InnovArul** [comment]
Thanks. Maybe they used 81 (half of actual mac disp).
