### ISSUE TITLE
Memory size about test on the SceneFlow Datasets

### ISSUE THREAD

**Issue by buqing2009** [JiaRenChang/PSMNet#65]
您好，请问在SceneFlow数据集上Test至少需要多少显存？或者是有没有什么方法可以在单个GTX1080上进行测试？

**Comment by JiaRenChang** [comment]
@buqing2009 
測試一對KITTI2015影像需要約4500 MB GPU memory (maxdisp = 192)
測試Scene flow應該是低於這個數字的
如果您在單張1080上跑測試集，可以試著把batchsize調為1

**Comment by buqing2009** [comment]
@JiaRenChang 
谢谢回复
