### ISSUE TITLE
Data Augmentation Issues

### ISSUE THREAD

**Issue by kingsleyluoxin** [JiaRenChang/PSMNet#70]
I noticed that in your codes, processed = preprocess.get_transform(augment=False)  , when it's training, your data are not augmented. I have been wondering if these augmentation skills will help to improve the accuracy?

**Comment by JiaRenChang** [comment]
Hi.
We only used random crop for training.
We have tried other image augmentation skills, such as color jittering and relighting, but it not help to improve.

**Comment by kingsleyluoxin** [comment]
Thanks so much for replying.
