### ISSUE TITLE
bad result when i use my own picture and pretrained model

### ISSUE THREAD

**Issue by Siming001** [JiaRenChang/PSMNet#74]
I use pretrained KITTI 2015 model to test my own picture, but I got some very bad results. Could you tell me where the problem is? Here is the KITTI picture and my own picture ,and I try to use the same setting with KITTI to take my own picture.
![000000_10](https://user-images.githubusercontent.com/38091470/44529454-bb6adb80-a71e-11e8-96fa-d25231bb2987.png)
![000008_10](https://user-images.githubusercontent.com/38091470/44529458-bf96f900-a71e-11e8-9838-b1277b989a44.png)
![000000_10](https://user-images.githubusercontent.com/38091470/44529486-caea2480-a71e-11e8-8076-c4f76d3721e2.png)
![000008_10](https://user-images.githubusercontent.com/38091470/44529496-cfaed880-a71e-11e8-8aa7-1387f872cbeb.png)

**Comment by JiaRenChang** [comment]
@Siming001 
This is a generalization problem.
We are making an effort to this problem, and we seem to have good results in the wild now.
When we finish, we will publish our new model.

**Comment by Siming001** [comment]
@JiaRenChang Thank you for tell me the reason.

**Comment by yxchng** [comment]
@JiaRenChang So your model only works on KITTI?
