### ISSUE TITLE
pretrained 'basic' models available?

### ISSUE THREAD

**Issue by aasharma90** [JiaRenChang/PSMNet#86]
Dear @JiaRenChang, 

By any luck you have the pre-trained models for the 'basic' version of PSMNet available? I am looking for the one trained on KITTI2015 specifically. Many thanks in advance if you could kindly provide it. 

Best regards!

**Comment by JiaRenChang** [comment]
Hi, @aasharma90 
 Sorry, we don't have any plans to upload the basic model.

**Comment by aasharma90** [comment]
Ok,, no worries. Thanks for your reply!
