### ISSUE TITLE
Why is there a problem with my disparity

### ISSUE THREAD

**Issue by hnsywangxin** [JiaRenChang/PSMNet#94]
Ｈello
       when I used submission.py to evaluation the model, I got a bad disparity,example:
![000018_10](https://user-images.githubusercontent.com/18531174/48831319-8881c380-edb1-11e8-8f7d-2d973d53bf1d.png)

I changed some parameters, otherwise it will cause my １080ti to be insufficient.
my data is KITTI  2015

my TrainImgLoader:
`batch_size= 4, shuffle= True, num_workers= 4, drop_last=False`
my TestImgLoader:
` batch_size= 2, shuffle= False, num_workers= 2, drop_last=False`
and my maxdisp is 96 not 192

I want to know why is this result ? it was caused by maxdisp?

and I used the pretrained_model_KITTI2015 ,I got the same result

Thank you very much!

**Comment by Huyhust13** [comment]
Dear @hnsywangxin , i'm facing the same problem. Could you share how to you fixed it?
